<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SignalAtlas.Domain\SignalAtlas.Domain.csproj" />
    <ProjectReference Include="..\SignalAtlas.Analyst\SignalAtlas.Analyst.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
